version: '3'
services:
    app:
        build: .
        ports:
            - '${PORT}:${PORT}'
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - '3306:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5
